---
title: "GSoC 2024 Week 12"
author: "Yinxiang Huang"
format: revealjs
editor: visual
---

## Coding Plan

Week 12(Plan):

-   Finish Issue [#69](https://github.com/Abhi-1U/texor/issues/69): Challenges in incorprating pseudocodejs to implement `algorithmic` environment

Week 12(Real):

-   fix Issues related to previous work

## What have been solved (by Abhishek)

-   fix Issue [#80](https://github.com/Abhi-1U/texor/issues/80): rnw_to_rmd: centre figures

## What have been solved (by Yinxiang Huang) {.smaller}

-   fix Issue [#76](https://github.com/Abhi-1U/texor/issues/76): More output options for `texor::rnw_to_rmd` (add output template for `BiocStyle` and `LiteDown`)

-   fix Issue [#81](https://github.com/Abhi-1U/texor/issues/81): rnw_to_rmd: suppress package startup messages

-   fix Issue [#87](https://github.com/Abhi-1U/texor/issues/87): Remove `web_only` parameter from yaml

-   fix Issue [#83](https://github.com/Abhi-1U/texor/issues/83): improve default sectioning

related: - fix Issue [#86](https://github.com/Abhi-1U/texor/issues/86): Section references are static

## Discussion {.smaller}

I checked css document and found that the reference to `counter` property's value is unavailable now. It is still an open issue.

So I use JavaScript instead to implement the same function. It is more flexible though more complex.

To make R Markdown document easiter to read, I insert the script as in-header HTML code.

## Discussion

- How to use test-coverage in github workflow?

- `texor` Logo in README file may not work?

## Next to do

-   test & merge Abhishek's lua filter for centering image

# Thank you!
