---
title: "GSoC 2024 Week 11"
author: "Yinxiang Huang"
format: revealjs
editor: visual
---

## Coding Plan

Week 11(Plan):

-   Finish Issue [#69](https://github.com/Abhi-1U/texor/issues/69): Challenges in incorprating pseudocodejs to implement `algorithmic` environment

Week 11(Real):

-   fix Issues related to previous work

## What have been solved (by Abhishek)

-   fix Issue [#80](https://github.com/Abhi-1U/texor/issues/80): rnw_to_rmd: centre figures


## What have been solved (by Yinxiang Huang)

-   fix Issue [#83](https://github.com/Abhi-1U/texor/issues/83): improve default sectioning

related:
-   fix Issue [#86](https://github.com/Abhi-1U/texor/issues/86): Section references are static

## Discussion 

Although Abhishek's lua filter works, it will permanently change the section level of the document and cannot fix the numbering style of equations. This is not what we want. We need to find a way to only change the font size without changing the section level.

So pandoc extension for css is a good choice. We can use css to change the font size of the section title while number the sections.

At last, we should change all dynamic reference for sections to static so that it won't show `??` in the output.

## Discussion 

```css
body {
  counter-reset: h1;
}

div.article h1::before {
  counter-increment: h1;
  content: counter(h1) " ";
  font-size: 30px;
}

div.article h1 {
  counter-reset: h2;
  font-size: 30px;
}

div.article h2 {
  counter-reset: h3;
}

div.article h2::before {
  counter-increment: h2;
  content: counter(h1) "." counter(h2) " ";
}

div.article h3::before {
  counter-increment: h3;
  content: counter(h1) "." counter(h2) "." counter(h3) " ";
}
```

## Next to do

-   embed additional css code into R Markdown output
-   test & merge Abhishek's lua filter for centering image

# Thank you!
